-- Shows total customers by countries
SELECT 
	country,
	COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Shows total customers by gender
SELECT 
	gender,
	COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Shows total products by category
SELECT 
	category,
	COUNT(product_name) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Shows average costs for each category
SELECT
	category,
	AVG(cost) as average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- Show total revenue generated for each category
SELECT
	p.category,
	SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Shows total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON c.customer_key = s.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- Shows total quantity of sold items by country
SELECT
    c.country,
    SUM(s.quantity) AS total_quantity
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;
